ninja.port=8081
# Demo secret only. Generate your own for production with 'mvn ninja:generateSecret'.
application.secret=RHwx0fWz73AlJx1fulfkrYKL5Yo7t8F1H8xUajByE28=
application.session.expire_time_in_seconds=3600
application.session.cookie.secure=false

# Database configuration
application.datasource.default.driver=org.h2.Driver
application.datasource.default.url=jdbc:h2:./tmp_db
application.datasource.default.username=sa
application.datasource.default.password=

# Flyway migration configuration
application.datasource.default.migration.enabled=true
application.datasource.default.migration.username=sa
application.datasource.default.migration.password=