<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.r10r</groupId>
        <artifactId>ninjax</artifactId>
        <version>0.3.2-SNAPSHOT</version>
    </parent>

    <artifactId>ninjax-db-hikari</artifactId>
    <name>ninjax-db-hikari</name>
    <description>Hikari connection pooling for ninja database modules</description>

    <dependencies>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninjax-db-common</artifactId>
        </dependency>
        <dependency>
            <groupId>com.zaxxer</groupId>
            <artifactId>HikariCP</artifactId>
        </dependency>
    </dependencies>
</project>