appname=superapp

application.secret=GWaGcjN76eiK6MJoG7qcoj5ZFfga6XZxluYGlm4qRTU=
# one week
application.session.expire_time_in_seconds=604800


# can be moved to 
application.datasource.default.driver=org.h2.Driver
application.datasource.default.url=jdbc:h2:./target/tmp_db
application.datasource.default.username=sa
application.datasource.default.password=

application.datasource.default.migration.enabled=true
application.datasource.default.migration.username=sa
application.datasource.default.migration.password=