<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.r10r</groupId>
        <artifactId>ninjax</artifactId>
        <version>0.2.15-SNAPSHOT</version>
    </parent>

    <artifactId>ninja-db-jdbi</artifactId>
    <name>ninja-db-jdbi</name>
    <description>JDBI database access layer for ninja database modules</description>

    <dependencies>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-db-common</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi3-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jdbi</groupId>
            <artifactId>jdbi3-sqlobject</artifactId>
        </dependency>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-core</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-jetty</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-db-hikari</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-db-flyway</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.r10r</groupId>
            <artifactId>ninja-template</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-api</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-params</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter-engine</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>