ninja.port=8081
application.secret=U29tZVJlYWxseVN0cm9uZ1NlY3JldEtleUZvckRlbW9QdXJwb3NlczEyMzQ1Njc4OTA=
application.session.expire_time_in_seconds=3600
application.session.cookie.secure=false

# Database configuration
application.datasource.default.driver=org.h2.Driver
application.datasource.default.url=jdbc:h2:./tmp_db
application.datasource.default.username=sa
application.datasource.default.password=

# Flyway migration configuration
application.datasource.default.migration.enabled=true
application.datasource.default.migration.username=sa
application.datasource.default.migration.password=